### PR TITLE
test_index updated, rename _add_index in collection.py and remove raw request from add_hash_index

### PR DESCRIPTION
**Pull request by edgargarciamacrometa**
## Description

Added test_add_ttl_index(), changed index_id by index_name in delete_index(), and modified some properties for assetion

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Reviews

Please identify two developers to review this change

- [x] @dlozina-macrometa 
- [x] @koshy-thomas 
- [x] @ricardo-macrometa 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added new functional tests that prove my fix is effective or that my feature works
- [x] Existing and new functional tests pass with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koshy-thomas** [comment]
@edgargarciamacrometa Great Work with the indexes!
 I just have minor suggestions:
 1. A small line to test get_index function can be added 
 2. _add_index needs to be checked I think the endpoint in api reference is /index/general but in our _add_index function we are using /index ... also it should be renamed to remove the _ at the start of the function name and finally few lines of test code can be added for the function.

**Review by dlozina-macrometa — COMMENTED** [review]
@edgargarciamacrometa please sync with @koshy-thomas and see his comment. Thanks!

**Comment by edgargarciamacrometa** [comment]
Changes were made team!

**Review by koshy-thomas — COMMENTED** [review]
@edgargarciamacrometa right now the endpoints we are using seem to be different than the API reference.. although the end point we are using does work.. but still I think we should sync the endpoints with API reference

The different indexes actually have different end points (like /index/fulltext) in the API reference.. 

@dlozina-macrometa So, maybe we can merge this PR and we open a separate Jira to make the API endpoint change in pyC8 for indexes (syncing with API ref) ?

**Review by koshy-thomas — APPROVED** [review]

**Comment by edgargarciamacrometa** [comment]
I think we might consult with someone about how are create index call is made. I understand what you mean, but I think we should consult if the specific index creation endpoints make use of the general index endpoint. If that is the case we might be doing an extra request when using specific index endpoint URL

**Comment by koshy-thomas** [comment]
> I think we might consult with someone about how are create index call is made. I understand what you mean, but I think we should consult if the specific index creation endpoints make use of the general index endpoint. If that is the case we might be doing an extra request when using specific index endpoint URL

@edgargarciamacrometa Indeed I will check with DB team on this why we have separate endpoints and what is the recommended approach. Also, for now we don't need to change anything here because I checked our UI and it is also using the common /index api which we are using. Also jsc8 and cli is also using the same /index api endpoint so as of now we don't have to change anything but I do see in some tickets mentioned that (/index) is an old way (which is still being used everywhere) so I will just ask DB team once about the difference between the two and why do we have two and which one is recommended to be used.

**Pull request merged**
