### PR TITLE
Spot collections

### PR DESCRIPTION
**Pull request by poorvamacrometa**
## Description

Added APIS to support Spot Collections feature.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on a 2-region federation.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by kartikeya-macrometa** [comment]
@poorvamacrometa here are my review comments (cc @PNarodeMacrometa ):

## Code-related review comments
1. `fabric.py` line 444 : The method param should be called `spot_creation_type` i.e singular, not plural. Having the parameter be a plural form of the noun implies to users that more than one can be specified. You should change this in the `README.md` and everywhere else it is referred to in the documentation.
2. `fabric.py` lines 497 through 501 : You should use the enum values instead of the direct strings when checking what `spot_creation_types` is set to.

## Documentation-related review comments
1. `fabric.py` pydoc comment block in lines 449-450 : Need a better explanation. This documentation will appear in the pyc8 API documentation so it cannot be vague or an afterthought - customers will use this documentation to understand what a particular method param is used for.
2. `fabric.py` around line 613 - you have added a new param called `spot_collection` to the `create_collection()` method but this param is missing in the pydoc block for the method.
3. `README.md` lines 289 and 303 - We **should not expose the `_mm` tenant string** anywhere in the documentation. Regular customers will not access this. If you check the rest of the README, you will not find any references to the _mm tenant. You should probably change Step 1 and Step 4 of your Spot Collections workflow to just have a comment saying that only the main system admin can perform these functions. Please verify this with @durgagokina 
4. `overview.rst` Lines 265 onwards - same as 3 above; we should not expose the `_mm` tenant.

**Comment by kartikeya-macrometa** [comment]
@poorvamacrometa in you latest commit to this PR, in `fabric.py` Line 147 - still refers to `PLUSAR_URL_PREFIX` (sic). I thought we had removed this entirely. It may be due to a merge conflict - the latest commit status above shows that there is a conflict. Please resolve any merge conflicts, fix anything that may have broken as a result of the conflict.

**Comment by poorvamacrometa** [comment]
@kartikeya-macrometa - Fixed merge conflicts. Also updated docs + pydoc as per your suggestions.

**Comment by kartikeya-macrometa** [comment]
@poorvamacrometa the diff of your latest commit looks good (I only looked at the diff, not the whole file - I trust that your conflict resolution was proper) - one final suggestion is to remove the quotes from `macrometa-admin` and `macrometa-password` if you want to actually leave the code in there. Removing the quotes will turn those items into python variables, so it will still be syntactically correct python code but will let users know that these variables refer to sensitive information that will not be given to them.

**Comment by poorvamacrometa** [comment]
@kartikeya-macrometa - I have run the smoke tests. Additonally I have tested the bug-fix and spot-collections separately as well. Im confident no code has been comprimised during merge.

**Comment by poorvamacrometa** [comment]
@kartikeya-macrometa  I have run the smoke tests locally. Additonally I have tested the bug-fix and spot-collections separately as well. Im confident no code has been compromised during the merge.

**Pull request merged**
