### PR TITLE
Update and rename test_database.py to test_fabric.py

### PR DESCRIPTION
**Pull request by edgargarciamacrometa**
## Description

update fabric test, deleted engine() and details() method assert, rename db

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Reviews

Please identify two developers to review this change

- [x] @koshy-thomas 
- [x] @dlozina-macrometa 
- [x] @ricardo-macrometa 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added new functional tests that prove my fix is effective or that my feature works
- [x] Existing and new functional tests pass with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koshy-thomas** [comment]
@edgargarciamacrometa just make sure all the fabric related methods are covered like say delete_fabric, update_spot_region, fabrics_detail, dclist, localdc

**Review by dlozina-macrometa — COMMENTED** [review]
@koshy-thomas does this merge works for you? I know that you mentioned that most of the tests are sorted out

**Comment by edgargarciamacrometa** [comment]
Added missing methods, I think we need to figure out the best way to test spot. From what I know it has to be a spot region in order to make that possible

**Comment by koshy-thomas** [comment]
> Added missing methods, I think we need to figure out the best way to test spot. From what I know it has to be a spot region in order to make that possible

@edgargarciamacrometa @dlozina-macrometa No worries we can merge this and I will add the test code for spot regions once this is merged

**Review by koshy-thomas — APPROVED** [review]

**Pull request merged**
